In [15]:
import pandas as pd

In [16]:
#1.获取数据
data = pd.read_csv('train.csv')
data

            row_id       x       y  accuracy    time    place_id
0                0  0.7941  9.0809        54  470702  8523065625
1                1  5.9567  4.7968        13  186555  1757726713
2                2  8.3078  7.0407        74  322648  1137537235
3                3  7.3665  2.5165        65  704587  6567393236
4                4  4.0961  1.1307        31  472130  7440663949
...            ...     ...     ...       ...     ...         ...
29118016  29118016  6.5133  1.1435        67  399740  8671361106
29118017  29118017  5.9186  4.4134        67  125480  9077887898
29118018  29118018  2.9993  6.3680        67  737758  2838334300
29118019  29118019  4.0637  8.0061        70  764975  1007355847
29118020  29118020  7.4523  2.0871        17  102842  7028698129

[29118021 rows x 6 columns]

In [3]:
#缩小范围 时间处理 过滤签到次数少的地点

In [17]:
#缩小范围
data = data.query('x <2.5 & x>2 & y<1.5 & y>1.0')
data

            row_id       x       y  accuracy    time    place_id
112            112  2.2360  1.3655        66  623174  7663031065
180            180  2.2003  1.2541        65  610195  2358558474
367            367  2.4108  1.3213        74  579667  6644108708
874            874  2.0822  1.1973       320  143566  3229876087
1022          1022  2.0160  1.1659        65  207993  3244363975
...            ...     ...     ...       ...     ...         ...
29115112  29115112  2.1889  1.2914       168  721885  4606837364
29115204  29115204  2.1193  1.4692        58  563389  2074133146
29115338  29115338  2.0007  1.4852        25  765986  6691588909
29115464  29115464  2.4132  1.4237        61  151918  7396159924
29117493  29117493  2.2948  1.0504        81   79569  1168869217

[83197 rows x 6 columns]

In [26]:
#处理时间
time_value = pd.to_datetime(data['time'],unit='s')
date = pd.DatetimeIndex(time_value)
data['day'] = date.day
data['weekday'] = date.weekday
data['hour'] = date.hour

C:\Users\86157\AppData\Local\Temp\ipykernel_24792\2084940065.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['day'] = date.day
C:\Users\86157\AppData\Local\Temp\ipykernel_24792\2084940065.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['weekday'] = date.weekday
C:\Users\86157\AppData\Local\Temp\ipykernel_24792\2084940065.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['hour'] = date.hour

In [27]:
data

,row_id,x,y,accuracy,time,place_id,day,weekday,hour
112,112,2.2360,1.3655,66,623174,7663031065,8,3,5
180,180,2.2003,1.2541,65,610195,2358558474,8,3,1
367,367,2.4108,1.3213,74,579667,6644108708,7,2,17
874,874,2.0822,1.1973,320,143566,3229876087,2,4,15
1022,1022,2.0160,1.1659,65,207993,3244363975,3,5,9
...,...,...,...,...,...,...,...,...,...
29115112,29115112,2.1889,1.2914,168,721885,4606837364,9,4,8
29115204,29115204,2.1193,1.4692,58,563389,2074133146,7,2,12
29115338,29115338,2.0007,1.4852,25,765986,6691588909,9,4,20
29115464,29115464,2.4132,1.4237,61,151918,7396159924,2,4,18
29117493,29117493,2.2948,1.0504,81,79569,1168869217,1,3,22

In [37]:
#过滤签到次数少的地点
place_count = data.groupby('place_id').count()['row_id']
place_count[place_count > 3].head()

place_id
1014605271    28
1015645743     4
1017236154    31
1024951487     5
1028119817     4
Name: row_id, dtype: int64

In [40]:
data[data['place_id'].isin(place_count[place_count > 3].index.values)]

,row_id,x,y,accuracy,time,place_id,day,weekday,hour
112,112,2.2360,1.3655,66,623174,7663031065,8,3,5
367,367,2.4108,1.3213,74,579667,6644108708,7,2,17
874,874,2.0822,1.1973,320,143566,3229876087,2,4,15
1022,1022,2.0160,1.1659,65,207993,3244363975,3,5,9
1045,1045,2.3859,1.1660,498,503378,6438240873,6,1,19
...,...,...,...,...,...,...,...,...,...
29115112,29115112,2.1889,1.2914,168,721885,4606837364,9,4,8
29115204,29115204,2.1193,1.4692,58,563389,2074133146,7,2,12
29115338,29115338,2.0007,1.4852,25,765986,6691588909,9,4,20
29115464,29115464,2.4132,1.4237,61,151918,7396159924,2,4,18
29117493,29117493,2.2948,1.0504,81,79569,1168869217,1,3,22

In [43]:
data_final = data[data['place_id'].isin(place_count[place_count > 3].index.values)]
data_final

,row_id,x,y,accuracy,time,place_id,day,weekday,hour
112,112,2.2360,1.3655,66,623174,7663031065,8,3,5
367,367,2.4108,1.3213,74,579667,6644108708,7,2,17
874,874,2.0822,1.1973,320,143566,3229876087,2,4,15
1022,1022,2.0160,1.1659,65,207993,3244363975,3,5,9
1045,1045,2.3859,1.1660,498,503378,6438240873,6,1,19
...,...,...,...,...,...,...,...,...,...
29115112,29115112,2.1889,1.2914,168,721885,4606837364,9,4,8
29115204,29115204,2.1193,1.4692,58,563389,2074133146,7,2,12
29115338,29115338,2.0007,1.4852,25,765986,6691588909,9,4,20
29115464,29115464,2.4132,1.4237,61,151918,7396159924,2,4,18
29117493,29117493,2.2948,1.0504,81,79569,1168869217,1,3,22

In [44]:
#筛选特征值和目标值
x = data_final[['x','y','accuracy','day','weekday','hour']]
y = data_final['place_id']
x

               x       y  accuracy  day  weekday  hour
112       2.2360  1.3655        66    8        3     5
367       2.4108  1.3213        74    7        2    17
874       2.0822  1.1973       320    2        4    15
1022      2.0160  1.1659        65    3        5     9
1045      2.3859  1.1660       498    6        1    19
...          ...     ...       ...  ...      ...   ...
29115112  2.1889  1.2914       168    9        4     8
29115204  2.1193  1.4692        58    7        2    12
29115338  2.0007  1.4852        25    9        4    20
29115464  2.4132  1.4237        61    2        4    18
29117493  2.2948  1.0504        81    1        3    22

[80910 rows x 6 columns]

In [49]:
#数据集分析
from sklearn.model_selection import train_test_split

In [50]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [51]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [55]:
#3.特征工程:标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)
#4.KNN算法预估器
estimator = KNeighborsClassifier()
#加入网格搜索与交叉验证
param_dict = {'n_neighbors':[1,3,5,7,9]}
estimator = GridSearchCV(estimator,param_grid=param_dict,cv=3)
estimator.fit(x_train,y_train)
#5.模型评估
#方法一：直接比对真实值预测值
y_predict = estimator.predict(x_test)
print('y_predict: \n',y_predict)
print('直接比对真实值和预测值: \n',y_test == y_predict)
#方法二:计算准确率
score = estimator.score(x_test,y_test)
print('准确率: \n',score)
print('最佳参数: \n',estimator.best_params_)
print('最佳结果:\n',estimator.best_score_)
print('最佳估计器: \n',estimator.best_estimator_)
print('交叉验证结果:\n',estimator.cv_results_)

C:\Users\86157\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(

y_predict:
 [4861093827 6709409787 4168031615 ... 1533408099 4233534513 1577178217]
直接比对真实值和预测值:
 4501705      True
15269680    False
21443553    False
15379170    False
16651693    False
            ...
1613437     False
22688894    False
20192801     True
2911334      True
16097989     True
Name: place_id, Length: 20228, dtype: bool
准确率:
 0.3543108562388768
最佳参数:
 {'n_neighbors': 1}
最佳结果:
 0.34275404242266855
最佳估计器:
 KNeighborsClassifier(n_neighbors=1)
交叉验证结果:
 {'mean_fit_time': array([0.03882949, 0.03670541, 0.03633587, 0.03612407, 0.03702323]), 'std_fit_time': array([0.00061459, 0.00129231, 0.00125142, 0.00096198, 0.00109462]), 'mean_score_time': array([0.68716462, 0.72798125, 0.77223833, 0.80930026, 0.82109292]), 'std_score_time': array([0.02408733, 0.00770878, 0.01818001, 0.01158207, 0.00688259]), 'param_n_neighbors': masked_array(data=[1, 3, 5, 7, 9],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'n_neighbors': 1}, {'n_neighbors': 3}, {'n_neighbors': 5}, {'n_neighbors': 7}, {'n_neighbors': 9}], 'split0_test_score': array([0.34195175, 0.32697251, 0.33636543, 0.33423967, 0.33191616]), 'split1_test_score': array([0.34449004, 0.32515944, 0.34083156, 0.33929896, 0.33539329]), 'split2_test_score': array([0.34182034, 0.31937509, 0.33450339, 0.33534385, 0.32901567]), 'mean_test_score': array([0.34275404, 0.32383568, 0.33723346, 0.33629416, 0.33210837]), 'std_test_score': array([0.00122871, 0.0032398 , 0.00265538, 0.00217201, 0.0026072 ]), 'rank_test_score': array([1, 5, 2, 3, 4])}