In [1]:
import pandas as pd
#1获取数据
#2合并表
#3找到user_id和aisle之间的关系
#4PCA降维

In [2]:
#1获取数据
order_products = pd.read_csv('order_products__prior.csv')
products = pd.read_csv('products.csv')
orders = pd.read_csv('orders.csv')
aisles = pd.read_csv('aisles.csv')

In [3]:
#2合并表
tab1 = pd.merge(aisles,products,on=['aisle_id','aisle_id'])
tab2 = pd.merge(tab1,order_products,on=['product_id','product_id'])
tab3 = pd.merge(tab2,orders,on=['order_id','order_id'])
tab3

,aisle_id,aisle,product_id,product_name,department_id,order_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1,prepared soups salads,209,Italian Pasta Salad,20,94246,5,0,114082,prior,26,0,20,1.0
1,1,prepared soups salads,209,Italian Pasta Salad,20,192465,2,1,119977,prior,2,0,16,3.0
2,1,prepared soups salads,209,Italian Pasta Salad,20,195206,18,1,1519,prior,7,2,9,5.0
3,1,prepared soups salads,209,Italian Pasta Salad,20,227717,1,1,161125,prior,7,2,11,11.0
4,1,prepared soups salads,209,Italian Pasta Salad,20,260072,13,0,12012,prior,5,5,11,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434484,134,specialty wines champagnes,49661,Porto,5,2238789,10,1,72244,prior,19,4,23,5.0
32434485,134,specialty wines champagnes,49661,Porto,5,2251344,5,1,72244,prior,18,6,10,9.0
32434486,134,specialty wines champagnes,49661,Porto,5,2616249,2,0,100075,prior,8,4,17,9.0
32434487,134,specialty wines champagnes,49661,Porto,5,2715237,1,0,135045,prior,3,6,14,30.0
32434488,134,specialty wines champagnes,49661,Porto,5,3263901,6,1,72244,prior,15,4,9,14.0

In [4]:
#3找到user_id和aisle之间的关系
tab = pd.crosstab(tab3['user_id'],tab3['aisle'])
tab3

,aisle_id,aisle,product_id,product_name,department_id,order_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1,prepared soups salads,209,Italian Pasta Salad,20,94246,5,0,114082,prior,26,0,20,1.0
1,1,prepared soups salads,209,Italian Pasta Salad,20,192465,2,1,119977,prior,2,0,16,3.0
2,1,prepared soups salads,209,Italian Pasta Salad,20,195206,18,1,1519,prior,7,2,9,5.0
3,1,prepared soups salads,209,Italian Pasta Salad,20,227717,1,1,161125,prior,7,2,11,11.0
4,1,prepared soups salads,209,Italian Pasta Salad,20,260072,13,0,12012,prior,5,5,11,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434484,134,specialty wines champagnes,49661,Porto,5,2238789,10,1,72244,prior,19,4,23,5.0
32434485,134,specialty wines champagnes,49661,Porto,5,2251344,5,1,72244,prior,18,6,10,9.0
32434486,134,specialty wines champagnes,49661,Porto,5,2616249,2,0,100075,prior,8,4,17,9.0
32434487,134,specialty wines champagnes,49661,Porto,5,2715237,1,0,135045,prior,3,6,14,30.0
32434488,134,specialty wines champagnes,49661,Porto,5,3263901,6,1,72244,prior,15,4,9,14.0

In [5]:
#4PCA降维
from sklearn.decomposition import PCA

In [6]:
#1实例化转化器类
transfer =  PCA(n_components=0.95)
#2调用fit_transform
data_new = transfer.fit_transform(tab)
data_new

array([[-24.21565875,   2.4294272 ,  -2.46636975, ...,  -0.08877715,
         -0.38087761,   0.21568831],
       [  6.46320808,  36.75111647,   8.38255337, ...,   1.912145  ,
          1.79468946,  -0.70142249],
       [ -7.99030162,   2.40438257, -11.03006405, ...,  -0.72188348,
         -1.15719089,  -0.23704277],
       ...,
       [  8.61143331,   7.70129866,   7.95240226, ...,   0.23971061,
         -0.78590175,  -2.65945606],
       [ 84.08621987,  20.41873398,   8.05410372, ...,  -1.66893212,
          0.5042934 ,   3.82546312],
       [-13.95345619,   6.64621821,  -5.23030367, ...,  -1.64144758,
         -3.39233648,  -0.31410713]])

In [7]:
data_new.shape

(206209, 44)

In [8]:
#预估器流程
from sklearn.cluster import KMeans

In [12]:
estimator = KMeans(n_clusters=3)
estimator.fit(data_new)

KMeans(n_clusters=3)

In [14]:
y_predict = estimator.predict(data_new)

In [17]:
y_predict[:300]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1,
       2, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1,
       1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2])

In [18]:
#模型评估-轮廓系数
from sklearn.metrics import silhouette_score

In [19]:
silhouette_score(data_new,y_predict)

0.5366059379157355